name: SeniorNPC
main: com.gmail.kurpfy.seniorteam.SeniorTeamPlugin
version: 1.0-SNAPSHOT
author: Kurpfy
website: http://github.com/SrKurpfy/SeniorTeamNPCs
commands:
  npc:
    permission: seniornpc.super